# Only one archetype (posts) is included in Hugo Starter
archetypedir = "archetypes"
baseurl = "http://localhost:1313"
buildDrafts = false
buildFuture = false
canonifyurls = true
config = "config.toml"
contentdir = "content"
disableLiveReload= false
disableRSS = false
disableSitemap = false
ignoreFiles = []
languageCode = "en-us"
layoutDir = "layouts"
log = false
metaDataFormat = "yaml"
publishdir = "public"
pygmentsUseClasses = true
relativeURLs = true
source = ""
title = "ryanwatters.io"
uglyURLs = false
verbose = true
verboseLog = false
watch = true

[permalinks]
  # The temp folder is created for one-off pages (eg, marketing and design-heavy pages that run outside other site templates). Keep in mind that all .md pages under temp still require title and date in the YAML/front matter
  singletons = "/:title/"

[params]
	SiteAuthor = "Ryan Watters"
  SiteTitle = "ryanwatters.io"
  TwitterHandle = "ryandwatters"
  #######BEGIN SOCIAL#######
  # For each social account, use the full URL that leads to the homepage of your account/profile
	GitHub = "https://github.com/rdwatters"
  Twitter = "https://twitter.com/@ryandwatters"
  #Include ID for Facebook App
  Facebook = "Ryan-Watters-810571539011577/"
  YouTube = "https://youtube.com"
  GooglePlus = "https://plus.google.com/"
  # For LinkedIn, you'll need to make sure you are using the URL for visitors, rather than the URL once you're signed into your account.
  LinkedIn = "https://linkedin.com"
  Instagram = "https://www.instagram.com"
  Tumblr = "https://www.tumblr.com/"
  Pinterest = "https://pinterest.com/"
  IncludeRSS = true
  # Add your Google Analytics ID here (ie, UA-XXXXXXXX-X). See layouts/partials/google_analytics.html. Dev environment (ie, localhost) is automatically disabled.
  GoogleAnalyticsTrackingId = "UA-76549364-1"
  #######END SOCIAL#######
  CopyrightLine = "Ryan Watters"
  SiteDescription = "The official site of Ryan Watters"
  UseCRP = true
  # Include jQuery 3.0 from assets/js
  IncludeJQ = true
  # Disqus two conditions (here and in page)
  UseDisqus = true
  disqusShortname = ""
  SitePublishDate = "2016-01-01"
  SiteTagline = "Content Strategist, Storyteller, Frontend Developer, Unabashed Nerd"
  #Leave off extension for default social image since it's assumed to be "jpg"
  DefaultSocialImage = "site-logo-default-social"
  # Setting this to true will include Swiftype Metadata in <head> and the default single.html <article> in layouts/_default
  Swiftype = false
  UpdatedText = "Updated:"

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"





