# Only one archetype (posts) is included in Hugo Starter
archetypedir = "archetypes"
baseurl = "/"
buildDrafts = false
buildFuture = false
canonifyurls = true
config = "config.toml"
contentdir = "content"
disableLiveReload= false
disableRSS = false
disableSitemap = false
ignoreFiles = []
languageCode = "en-us"
layoutDir = "layouts"
log = false
metaDataFormat = "yaml"
preserveTaxonomyNames = false
publishdir = "public"
pygmentsUseClasses = true
relativeURLs = true
source = ""
staticdir = "static"
title = "ryanwatters.io"
uglyURLs = false
verbose = false
verboseLog = false
watch = true

[permalinks]
  # The temp folder is created for one-off pages (eg, marketing and design-heavy pages that run outside other site templates). Keep in mind that all .md pages under temp still require title and date in the YAML/front matter
  singles = "/:title/"

[params]
	SiteAuthor = "Ryan Watters"
  SiteTitle = "ryanwatters.io"

  #######BEGIN SOCIAL#######
	GitHub = "https://github.com/rdwatters"
  Twitter = "https://twitter.com/@ryandwatters"
  #Include Twitter Handle without the "@"
  TwitterHandle = "ryandwatters"
  #Include ID for Facebook App
  Facebook = "Ryan-Watters-810571539011577/"
  YouTube = "https://youtube.com"
  GooglePlus = "https://plus.google.com/"
  # For LinkedIn, use the URL for visitors (ie, when you're not signed in). Include everything after "https://www.linkedin.com/in/"
  LinkedIn = "ryan-watters-els-08010725"
  IncludeRSS = true
  # Add your Google Analytics ID here (ie, UA-XXXXXXXX-X). See layouts/partials/site_footer/google_analytics.html. Dev environment (ie, localhost) and netlify urls are automatically disabled.
  GoogleAnalyticsTrackingId = "UA-76549364-1"
  #######END SOCIAL#######
  copyrightline = "Ryan Watters"
  sitedescription = "The official site of Ryan Watters"
  usecrp = true
  # Include jQuery 2.x from assets/js
  includejq = false
  # Disqus has two conditions (here and in page); setting this to "false" will turn off comments on ALL pages
  usedisqus = true
  disqusshortname = "ryanwattersio"
  sitepublishdate = "2016-01-01"
  sitetagline = "Content Strategist, Storyteller, Frontend Developer, Unabashed Nerd"
  #Leave off extension for default social image since it's assumed to be "jpg"
  defaultsocialimage = "site-logo-default-social.jpg"
  #Word used in Pub Date partial to denote whether a post has been updated
  updatedtext = "Updated:"
  # Determines style of previous and next links in /posts; options are either "sides" or "bottom"
  PostPrevNextStyle = "bottom"

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true
  sourceRelativeLinksEval = false

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"





